export const ALL_FOODITEM_REQUEST = "ALL_FOODITEM_REQUEST";
export const ALL_FOODITEM_SUCCESS = "ALL_FOODITEM_SUCCESS";
export const ALL_FOODITEM_FAIL = "ALL_FOODITEM_FAIL";

export const FOODITEM_DETAILS_REQUEST = "FOODITEM_DETAILS_REQUEST";
export const FOODITEM_DETAILS_SUCCESS = "FOODITEM_DETAILS_SUCCESS";
export const FOODITEM_DETAILS_FAIL = "FOODITEM_DETAILS_FAIL";

export const ADMIN_FOODITEM_REQUEST = "ADMIN_FOODITEM_REQUEST";
export const ADMIN_FOODITEM_SUCCESS = "ADMIN_FOODITEM_SUCCESS";
export const ADMIN_FOODITEM_FAIL = "ADMIN_FOODITEM_FAIL";

export const NEW_FOODITEM_REQUEST = "NEW_FOODITEM_REQUEST";
export const NEW_FOODITEM_SUCCESS = "NEW_FOODITEM_SUCCESS";
export const NEW_FOODITEM_RESET = "NEW_FOODITEM_RESET";
export const NEW_FOODITEM_FAIL = "NEW_FOODITEM_FAIL";

export const DELETE_FOODITEM_REQUEST = "DELETE_FOODITEM_REQUEST";
export const DELETE_FOODITEM_SUCCESS = "DELETE_FOODITEM_SUCCESS";
export const DELETE_FOODITEM_RESET = "DELETE_FOODITEM_RESET";
export const DELETE_FOODITEM_FAIL = "DELETE_FOODITEM_FAIL";

export const UPDATE_FOODITEM_REQUEST = "UPDATE_FOODITEM_REQUEST";
export const UPDATE_FOODITEM_SUCCESS = "UPDATE_FOODITEM_SUCCESS";
export const UPDATE_FOODITEM_RESET = "UPDATE_FOODITEM_RESET";
export const UPDATE_FOODITEM_FAIL = "UPDATE_FOODITEM_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
