export const ALL_FOODITEM_REQUEST = "ALL_FOODITEM_REQUEST";
export const ALL_FOODITEM_SUCCESS = "ALL_FOODITEM_SUCCESS";
export const ALL_FOODITEM_FAIL = "ALL_FOODITEM_FAIL";

export const FOODITEM_DETAILS_REQUEST = "FOODITEM_DETAILS_REQUEST";
export const FOODITEM_DETAILS_SUCCESS = "FOODITEM_DETAILS_SUCCESS";
export const FOODITEM_DETAILS_FAIL = "FOODITEM_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";